INSERT INTO brand (id, name) VALUES (1, 'BRAND-1');
INSERT INTO brand (id, name) VALUES (2, 'BRAND-2');
INSERT INTO brand (id, name) VALUES (3, 'BRAND-3');
INSERT INTO brand (id, name) VALUES (4, 'BRAND-4');
INSERT INTO location (id, name, brand_id) VALUES (1, 'Delhi', 1);
INSERT INTO location (id, name, brand_id) VALUES (2, 'Mumbai', 1);
INSERT INTO location (id, name, brand_id) VALUES (3, 'Delhi', 2);
INSERT INTO location (id, name, brand_id) VALUES (4, 'Kolkata', 3);
INSERT INTO location (id, name, brand_id) VALUES (5, 'Bangalore', 3);
INSERT INTO location (id, name, brand_id) VALUES (6, 'Chandigarh', 3);